### ISSUE TITLE
Converting to React.js

### ISSUE THREAD

**Issue by bahaa96** [Tarteel-io/tarteel-api#153]
#### MileStone: 
- [ ] Content Security Policy
- [ ] Making configFactory ready for production
- [ ] use modernizr
- [ ] make a serviceWorker
- [ ] Having a pre-commit script
- [ ] Make a README.md for the main project
- [ ] make a documentation for the APP if there’s more time 
- [ ] add a template for submitting new issues and PRs

#### Done: 
- [x] get the dev server running 
- [x] Regenerating dll files
- [x] intlprovider 
- [x] make locale parameter working 
- [x]  review Config factory
- [x] theme provider
- [x] link bootstrapper with the store before rendering.
- [x] ge eslint running 
- [x] use TS 
- [x] async component loading 
- [x]  use ServerHTML file
- [x] styled-components
