### ISSUE TITLE
Backend Refactoring To-Do List

### ISSUE THREAD

**Issue by piraka9011** [Tarteel-io/tarteel-api#188]
- [ ]  Refactor model endpoints to use [viewsets](https://www.django-rest-framework.org/api-guide/viewsets/) (Reason is: simplicity and most of the work is taken care of already, allowing us to work on filtering and features) (GET/POST/PUT/DELETE/PATCH)
    - [x] Annotated Recordings 
    Filters:
       - [x]  Gender
       - [x]  Surah
       - [x]  Ayah
    - [ ] Demographics
    Filters:
       - [ ]  Gender
       - [ ]  Surah
       - [ ]  Ayah
       - [ ]  Qiraah
       - [ ]  Ethnicity
       - [ ]  Age

- [x] Provide `zappa_dev/prod.json` with S3 bucket info and CI

- [x] Tests for Travis CI

- [x] Django fixtures and/or test DB for development

- [x] Write documentation for Zappa + Front end deployment

- [x] Remove unnecessary static assets

**Comment by piraka9011** [comment]
@AymenQ

**Comment by arasdean** [comment]
@piraka9011 it seems like the Demographics ViewSets have been added and merged no?

**Comment by piraka9011** [comment]
This was completed and updated yesterday. Check out the other issues or feel free to message me :)
